- pkg/util/util.go
@dfeldick @vivekschauhan @kflan-io @jcollins-axway please review
> APIGOV-17281 - add util func to peel out url host

- README.md
Added a note that Gol must be installed with a link to the install page to golang.org
> Go must be installed

- .csr-profile.json
- .gitlab-ci.yml
Cleaned up gitlab-ci file
Added to .csr-profile.json
> Apigov 17450

- pkg/cmd/root.go
- pkg/cmd/service/service.go
Also setting network-online.target as dependency to setup as systemd service
> APIGOV-17399 - Using path.config flag to setup config file path for TA

- CODEOWNERS
- README.md
- go.mod
- go.sum
- pkg/jobs/README.md
- pkg/jobs/baseJob.go
- pkg/jobs/basejob_test.go
- pkg/jobs/definitions.go
- pkg/jobs/intervaljob.go
- pkg/jobs/intervaljob_test.go
- pkg/jobs/jobs.go
- pkg/jobs/jobs_test.go
- pkg/jobs/pool.go
- pkg/jobs/pool_test.go
- pkg/jobs/retryjob.go
- pkg/jobs/retryjob_test.go
- pkg/jobs/scheduledjob.go
- pkg/jobs/scheduledjob_test.go
- pkg/jobs/util.go
- vendor/github.com/gorhill/cronexpr/APLv2
- vendor/github.com/gorhill/cronexpr/GPLv3
- vendor/github.com/gorhill/cronexpr/README.md
- vendor/github.com/gorhill/cronexpr/cronexpr.go
- vendor/github.com/gorhill/cronexpr/cronexpr_next.go
- vendor/github.com/gorhill/cronexpr/cronexpr_parse.go
- vendor/modules.txt
Maybe we have code review via teams?
> APIGOV-17664

- go.mod
- go.sum
- pkg/apic/apiserviceinstance.go
- pkg/apic/service_test.go
- pkg/apic/testdata/petstore-openapi2.yaml
- vendor/github.com/getkin/kin-openapi/openapi2/openapi2.go
- vendor/modules.txt
Add sdk support for oas2 yaml based spec definitions.
Update sdk and unit tests
> APIGOV-17786 - [SDK] as discovery, I need to support more yaml based spec definitions

- pkg/apic/mocksubscription.go
- pkg/apic/subscription.go
- pkg/apic/subscriptionbuilder.go
- pkg/apic/subscriptionbuilder_test.go
- pkg/apic/subscriptionschema.go
- pkg/apic/subscriptionschemabuilder.go
- pkg/apic/subscriptionschemabuilder_test.go
- pkg/apic/subscriptionschemapropertybuilder.go
- pkg/apic/subscriptionschemapropertybuilder_test.go
- pkg/apic/testdata/catalogitemsubscriptiondefprofile2.json
These still need enhanced and documented for use.
> APIGOV-17409 - added some builders for subscription handling

- pkg/apic/apiserviceinstance.go
Turned into mostly a sonar fix to satisfy those reported cog errors.  This code and go file will eventually get pancaked by code that Vivek is doing.  Most of the story's acceptance criteria was met by trevor's check in.  
Please review @dfeldick @jcollins-axway @kflan-io @vivekschauhan
> APIGOV-17868 - error and sonar update

- pkg/jobs/intervaljob.go
The interval job is ran prior to waiting the first interval
> APIGOV-17897 - run interval job once

- pkg/apic/servicebuilder.go
- pkg/apic/servicebuilder_test.go
@dfeldick, @sbolosan, @jcollins-axway , @kflan-io 
Please review
> APIGOV-18031 - Fix for trimming description to supported max length

- pkg/apic/subscription.go
- pkg/apic/subscriptionschemapropertybuilder.go
> APIGOV-18053 - filter out duplicate enum values for subscription definitions

- pkg/agent/agent.go
@dfeldick @kflan-io @jcollins-axway @vivekschauhan please review for fix of https://jira.axway.com/browse/APIGOV-18004
> APIGOV-18072 - update res and add setter for team

- pkg/apic/client.go
@jcollins-axway @sbolosan @kflan-io please review
> APIGOV-17994 - remove call to set attribute

- pkg/agent/agent.go
@jcollins-axway @kflan-io @vivekschauhan @dfeldick please review.
This is going under the assumption that local config takes precedence over resource config.
> APIGOV-18136 - set config team name

- pkg/api/client.go
- pkg/apic/auth/apicauth.go
Further triage to 1131 - authentication token was not valid
> Apigov 18286

- pkg/agent/discoverycache.go
- pkg/api/client.go
1. increase the client timeout from 30 to 60. There is a future story to make this configurable.  But for now, increase to 60
2. check on externalAPIID
> APIGOV-18379 - updates for primary and secondary key

- pkg/apic/apiservice_test.go
- pkg/apic/apiservicerevision.go
- pkg/apic/definitions.go
- pkg/apic/servicebuilder.go
- pkg/apic/servicebuilder_test.go
> Apigov api revision

- pkg/transaction/eventgenerator.go
1. use traffic aggregration
2. use CreateEvents for sampling
> APIGOV-19255 - enable aggregation

- pkg/agent/discovery.go
- pkg/agent/discovery_test.go
- pkg/agent/discoverycache.go
- pkg/apic/apiserviceinstance.go
- pkg/apic/client.go
- pkg/apic/service.go
> APIGOV-19718 - fix clean of api service instance, refresh cache on api validator registration 

- pkg/config/subscriptionconfig.go
My bad... forgot to update default for {{.Tag}}.  At least it was caught on start up by the validateCfg() ;)
> APIGOV-19862 - update defaults for {{.Tag}}

- errors.md
- pkg/apic/consumerinstance.go
- pkg/apic/errors.go
> APIGOV-19515 - add team name mismatch error

- pkg/apic/consumerinstance.go
X found a problem in with the substitution of the error messages.
> APIGOV-19886 - fix problem found in testing

- pkg/cmd/agentversionjob.go
1. If we cannot connect to jfrog or decode htmlAnchors, return err
2. However, when we return error, warn only that we could not get version and continue instead of bubbling up error
> APIGOV-20587 - warn that we could not get version from jfrog

- pkg/cmd/agentversionjob.go
- pkg/cmd/root.go
> AgentSDK-218 - update version checker to use central config proxy

- pkg/cmd/properties/resolver/secretResolver.go
If usage offline report on, then do not resolve @Secret
> APIGOV-20960 - if usage offline reporting on, return error for @Secret

- pkg/apic/auth/apicauth.go
Based on iteration triage with Peter O.  deciding to leave token locking in
> APIGOV-20991 - leave token locking and debug updates

- pkg/util/log/loggerconfig.go
only initialize the logging hooks once
> APIGOV-21082 - only initialize the logger output once, on startup

- pkg/api/client.go
- pkg/traceability/condorhealthcheckjob.go
- pkg/traceability/httpclient.go
- pkg/traceability/traceability.go
- pkg/traceability/traceability_test.go
- pkg/util/log/log.go
- update http connection
- add TLS properties
- fix tests
> APIGOV-21054 - update http connection

- docs/discovery/index.md
- pkg/agent/agent.go
- pkg/agent/discovery.go
- pkg/agent/discoverycache.go
- pkg/apic/apiserviceinstance.go
- pkg/apic/apiservicerevision.go
- pkg/apic/consumerinstance.go
- pkg/apic/definitions.go
- pkg/apic/service.go
- pkg/apic/servicebuilder.go
- added new service body attribute for changing the descriptor of a stage on an API Service and Catalog, default Stage
- added ability to add different attributes to API Service vs API Revision vs API Instance
> APIGOV-21043 - service builder changes for Apigee agent

- pkg/config/usagereportingconfig.go
- pkg/config/usagereportingconfig_test.go
- pkg/traceability/sampling/definitions.go
- pkg/traceability/sampling/globalsampling.go
- pkg/traceability/sampling/sampling_test.go
- pkg/transaction/definitions.go
- pkg/transaction/logeventbuilder.go
- pkg/transaction/logeventbuilder_test.go
> Revert "APIGOV-19455 Add a field in transaction summary event to indicate tha…"

- pkg/agent/agent.go
- pkg/agent/agent_test.go
- pkg/agent/discovery_test.go
- pkg/apic/service.go
- pkg/apic/subscriptionmanager.go
- pkg/util/errors/errors.go
Register subscription webhooks in agent init when configured by an agent.
> APIGO-21374 Add call to RegisterSubscriptionWebhook in agent init

- errors.md
- go.mod
- go.sum
- update library
- also fix problems in errors.md
> APIGOV-21468 - update gjson library

- pkg/apic/subscriptionmanager.go
> Fixes #295

- pkg/agent/agent_test.go
- pkg/agent/cache/manager.go
- pkg/agent/cache/manager_test.go
- pkg/agent/discovery_test.go
- pkg/agent/discoverycache.go
- pkg/agent/handler/handlers.go
- pkg/agent/handler/handlers_test.go
- pkg/agent/instancevalidator.go
- pkg/agent/instancevalidator_test.go
- pkg/agent/resource/manager_test.go
- pkg/agent/teamcache_test.go
- pkg/apic/apiservice.go
- pkg/apic/apiservicerevision.go
- pkg/apic/client.go
- pkg/apic/consumerinstance.go
- pkg/apic/definitions.go
- pkg/apic/definitions/definitions.go
- pkg/apic/service.go
- pkg/apic/subscriptionmanager.go
- pkg/apic/subscriptionmanager_test.go
- pkg/cmd/cmd_test.go
My original APIGOV-21493 branch was branched off of grpc-dev. Trying to pull in main has many merge conflicts. I'm looking to merge this change to main to try and make my merge conflicts easier. For my branch I needed to move a few types to a new package to avoid a circular dependency. Moving the types caused changes in a lot of files, so if I can get this into main and then try to merge again it should be easier.
> APIGOV-21493_tmp create definitions package

- pkg/apic/subscriptionmanager.go
> APIGOV-12345 - only log info subscriptions if agent is going to take action

- docs/discovery/subscriptions.md
- pkg/apic/mocksubscription.go
- pkg/apic/subscription.go
- pkg/apic/subscription_test.go
- pkg/apic/subscriptionschema.go
- pkg/apic/subscriptionschemapropertybuilder.go
- pkg/apic/subscriptionschemapropertybuilder_test.go
- Add CHANGE_REQUESTED state
- Add SetDefaultValue in subscriptionschema and subscriptionschemapropertybuilder
- Implement GetPropertyValues
> Streams 2477 Add methods and state in subscription/subscriptionschema

- pkg/agent/discoverycache.go
- pkg/agent/handler/traceaccessrequest.go
- pkg/agent/handler/traceaccessrequest_test.go
- pkg/apic/definitions/definitions.go
- pkg/apic/definitions/util.go
- pkg/apic/definitions/util_test.go
- pkg/transaction/metric/definition.go
- pkg/transaction/metric/metricscollector.go
- pkg/transaction/metric/metricscollector_test.go
- Changes to use references sub resource in AccessRequest to lookup associated subscription 
- Changes to use marketplace sub resource in ManagedApplication to lookup consumer org identifier
> APIGOV-21522 - Lookup for subscription and consumer orgID

- docs/discovery/index.md
- docs/traceability/index.md
- errors.md
- pkg/agent/agent_test.go
- pkg/agent/handler/accessrequest.go
- pkg/agent/handler/accessrequest_test.go
- pkg/agent/handler/credential.go
- pkg/agent/handler/credential_test.go
- pkg/apic/apiserver/clients/api/v1/client_test.go
- pkg/cmd/cmd_test.go
- pkg/config/authconfig.go
- pkg/config/centralconfig.go
- pkg/config/centralconfig_test.go
- pkg/config/errors.go
- pkg/traceability/traceability_test.go
- pkg/transaction/metric/metricscollector_test.go
- raise deprecation warning if DOSA_ is used
- throw config error if DOSA is used with Marketplace Provisioning
- Return error status for Access Request and Credential when linked Managed App not Success
> APIGOV-22377 - updates for handling marketplace provisioning error paths

- .gitignore
- pkg/agent/handler/accessrequest.go
- pkg/agent/handler/credential.go
- pkg/agent/handler/managedapplication.go
Logging the error status when provisioning of an AccessRequest, Credential, or ManagedApplication fails
> APIGOV-0012 update logging for mp event errors

- pkg/agent/provisioning.go
- pkg/migrate/marketplacemigration.go
Check ARD existence in both the migration and provisioning
> APIGOV-22693 - regression fixes

- pkg/cmd/properties/properties.go
- pkg/config/centralconfig.go
Kickback from testing
1. handle usage reporting when set/unset for DA and TA respectively
2. change logic to see if default actually equals lower limit (of 30s)
> APIGOV-22791 - changes from QA testing

- pkg/config/centralconfig.go
- pkg/config/usagereportingconfig.go
- pkg/config/usagereportingconfig_test.go
- pkg/util/healthcheck/healthchecker.go
1. refactor to use getter for usage reporting
2. fix nil pointer
> APIGOV-22792 - TA fixes from QA testing

- pkg/config/centralconfig.go
fix logic sequence for usage reporting
> APIGOV-22793 - fix QA test failure for usagereporting

- pkg/apic/provisioning/mock/provisioning.go
Hi,
I updated the provisioning mocks (ApplicationRequest/AccessRequest/CredentialRequest) with the recently added ID and AccessRequestProvisioningData attributes.
Regards,
Romain.
> feat(provisioning): add missing ID and AccessRequestProvisioningData attributes in mocks.

- pkg/agent/eventsync.go
@tsjohns9 @jcollins-axway  - haven't tested yet. My environment is having issues running Madhuri's stuff... So, just initial thoughts of where I'm doing this check.
> APIGOV-22912 - run migration only for DA and governance

- .github/workflows/tests-action.yml
- Makefile
> APIGOV-dale

- pkg/agent/cache/manager.go
- pkg/agent/discovery.go
- pkg/agent/eventsjob.go
- pkg/agent/eventsync.go
- pkg/agent/poller/client.go
- pkg/agent/poller/poller.go
- pkg/agent/stream/client.go
- pkg/apic/servicebody.go
- pkg/apic/servicebuilder.go
- pkg/jobs/pool.go
- pkg/migrate/ardmigration.go
- pkg/migrate/ardmigration_test.go
- New migration to remove scopes from any ARD
> APIGOV-22891 Remove "scopes" field in ARD for oauth resources with a new migration

- pkg/agent/agent.go
- pkg/agent/cache/apiservice.go
- pkg/agent/poller/poller.go
- pkg/agent/statusupdate.go
- pkg/authz/oauth/provider.go
- pkg/authz/oauth/providerregistry.go
- pkg/jobs/baseJob.go
- pkg/jobs/pool.go
- pkg/traceability/traceability.go
- pkg/transaction/eventgenerator.go
- pkg/transaction/metric/metricscollector.go
- pkg/util/log/trace.go
- samples/watchclient/pkg/client/client.go
WithField standard, lower case with "-" (dashes)
> APIGOV-23039 - standardize WithField

- pkg/transaction/eventgenerator.go
- pkg/transaction/logeventbuilder.go
- pkg/transaction/logeventbuilder_test.go
- pkg/transaction/metric/metricscollector.go
- pkg/transaction/models/definitions.go
Spoke with Levan and Romain - add product version id and keep product version name... 
landed on versionName and versionId for the key values.
> APIGOV-23178 - add product version id

- pkg/agent/hcjob.go
Update log message when central health check is failing
> APIGOV-0321 update

- pkg/agent/agent.go
- pkg/agent/discovery.go
- pkg/agent/eventsync.go
- pkg/agent/instancevalidator.go
- pkg/agent/instancevalidator_test.go
- pkg/jobs/channeljob.go
- pkg/jobs/pool.go
Fix for executing instance validator with DA only after the validator is setup
> APIGOV-23312 - Fix for setting up instance validator

- pkg/agent/discoverycache.go
add debug statement for QA so that we know its the correct sdk
> APIGOV-24680 - debug statement for QA

- pkg/agent/cache/apiservice.go
- pkg/agent/cache/manager_test.go
- pkg/agent/cache/migratepersistedcache_test.go
- pkg/agent/discoverycache.go
1. refactor instance count func
2. revert func order execution
3. update cache tests
> APIGOV-23717 - refactor instance count func

- pkg/transaction/eventgenerator.go
revert from code smell for now.
values are not get set properly when calling into the func for sampling key.  Will address later
> APIGOV-44444 - revert sampling key

- go.mod
> SB002 - in prep for next release, retract 35 and 36

- pkg/agent/cache/apiservice.go
SB001 - remove old logging for debug purposes.  Left over, not needed...
> SB001 - remove unnecessary QA debug now.

- pkg/apic/servicebuilder.go
set default for this bool to true
>  APIGOV-24591 - set req def allowed to default true

- pkg/agent/discovery.go
- pkg/apic/service.go
when payload is over 10mb, log publish service error and return it up stream
> APIGOV-24821 - bubble up error from publish api

- pkg/apic/apiserver/models/management/v1alpha1/Dataplane.go
- pkg/apic/apiserver/models/management/v1alpha1/model_dataplane_spec.go
Updated api-server model to use secretschema subresource in Dataplane
> APIGOV-24514 - Updated api-server model 

- pkg/cmd/root.go
> APIGOV-25570 - check for offline mode before checking status

- pkg/apic/apiserver/models/management/v1alpha1/model_dataplane_spec_aws.go
- pkg/transaction/metric/metricscollector.go
- additionally add way to exit metric init function
> APIGOV-25441 - codegen from api server updates

- pkg/agent/agent.go
- pkg/cmd/root.go
- pkg/util/healthcheck/healthchecker.go
- Changes to run periodic healthcheck in docker as well
- Chagnes to with exit code when running with --status flag
> APIGOV-25780 - Updates for healthcheck

- pkg/transaction/eventgenerator.go
When in offline mode, the client isn't being set (and doesn't need to be).  Check for nil ...
> APIGOV-26331 - check to make sure client is not nil

- pkg/agent/eventsync.go
> APIGOV-26551 - publishing lock when rebuilding cache

- pkg/agent/agent.go
- pkg/agent/discovery.go
- pkg/agent/provisioning.go
- pkg/apic/provisioning/propertybuilder.go
- pkg/apic/provisioning/schemabuilder.go
Update builders to coincide with CRD, external oauth (idP) changes in v7.
> APIGOV-26586 - update builders

- pkg/agent/agent.go
- pkg/agent/eventsync.go
- samples/watchclient/pkg/client/client.go
- Fix to register CRD for configured external IDPs after the cache initialization
- Includes fix for sample watch client
> INT - Fix for CRD registration

- pkg/agent/agent.go
- pkg/agent/cache/manager.go
- pkg/agent/cache/teams.go
- pkg/agent/teamcache.go
This update to the sdk is in preparation for the v7 agent to call RefreshTeamCache.
> APIGOV-26767 - refresh team cache

- pkg/apic/provisioning/propertybuilder.go
- pkg/apic/provisioning/propertybuilder_test.go
marketplace scopes fix (hopefully)
> APIGOV-26213 - Issue in adding scopes in marketplace client creation page

- pkg/agent/eventsjob.go
- pkg/agent/stream/client.go
- pkg/watchmanager/client.go
- includes fix to cleanup goroutines started for watch
> APIGOV-27048 - Fix to skip resetting timer with negative duration

- docs/traceability/index.md
Update sampling percentage description
> APIGOV-26592 - Update index.md 

- scripts/apiserver/generate.js
add _embedded to the filter fields.
> APIGOV-EmbeddedFix - filter out _embedded

- pkg/util/exception/exception.go
- pkg/util/exception/exeception_test.go
NOTE: this explains the panic error at start-up, but doesn't solve it
> APIGOV-27289 - more informative NPE

- pkg/transaction/metric/metricscollector.go
Add interface to initialize the metric batch
> APIGOV-000000 - Fix nil panic for metric batch

- pkg/agent/provisioning.go
- pkg/apic/provisioning/propertybuilder.go
- pkg/apic/provisioning/propertybuilder_test.go
- pkg/apic/provisioning/schemabuilder.go
- pkg/apic/provisioning/schemabuilder_test.go
- Changes to setup dependent properties for string based schema properties
- Updates to generate property and schema dependencies
- Updated OAuth external CRD to setup dependencies for private_key_jwt and tls_client_auth grant types
> APIGOV-26190 - Update to set property dependencies using schema builder

- pkg/agent/provisioning.go
- pkg/apic/provisioning/propertybuilder.go
- pkg/apic/provisioning/propertybuilder_test.go
- pkg/apic/provisioning/schemabuilder.go
- pkg/apic/provisioning/schemabuilder_test.go
> Revert "APIGOV-26190 - Update to set property dependencies using schema builder"

- pkg/authz/oauth/authclient.go
- pkg/authz/oauth/authclient_test.go
- pkg/authz/oauth/mockidpserver.go
- pkg/authz/oauth/provider.go
- pkg/authz/oauth/provider_test.go
- pkg/config/externalidpconfig.go
- Added new IdP configuration to setup request headers and query params for DCR calls
- Added new IdP auth configuration to setup request headers and query params in call to fetch token from IdP
> APIGOV-28134 - Additional request header and query param for DCR calls

- pkg/apic/specoas3processor.go
This solves a NPE due to a struct from the kin.openapi package having a field changed to a pointer
> APIGOV-DG000 fix NPE on spec.components

- errors.md
- pkg/apic/errors.go
Dead subscription code and markdown (for errors)
> APIGOV-SB321 - remove dead subscription error code

- pkg/apic/apiserviceinstance.go
- pkg/apic/mockserviceclient.go
- pkg/apic/servicebody.go
- pkg/config/centralconfig.go
- pkg/config/credentialconfig.go
- filter and sort order for internal OAuth CRD types to be allowed when associating to instance
> APIGOV-28733 - config for internal OAuth methods

- pkg/apic/definitions.go
> APIGOV-28764 - add backstage dataplane type

- pkg/filter/callexpr.go
- pkg/filter/conditionparser.go
- pkg/filter/data.go
- pkg/filter/expr_matchregex.go
- pkg/filter/filter.go
- pkg/filter/filter_test.go
- Added support for tag.MatchRegEx to filter based on reg for tag names
- Added support to filter with tag name having dashes
> APIGOV-28892 - Filter on tag with dashes in name

- pkg/agent/agent.go
- pkg/agent/resource/manager.go
- includes extra logging around status update when skipping update
> APIGOV-29069 - additional check to re-initialize agent resource if not set

- pkg/apic/provisioning/mock/provisioning.go
Added to credential request mock the method to get credential expiry days needed in provisioning testing
> APIGOV-29367 add method for testing purposes

- pkg/apic/components.go
- pkg/apic/definitions.go
Add WSO2 dataplane type to the epic branch
> APIGOV-29540 - add WS02 dataplane type

- pkg/agent/agent.go
- pkg/agent/discoverycache.go
- pkg/agent/eventsync.go
- pkg/agent/provisioning.go
- pkg/authz/oauth/providerregistry.go
- pkg/cmd/root.go
- Update the startup logic in regards to IDP, Cred Mapping, and Marketplace Resource Handling
> APIGOV-29684 - Update startup logic order of operations

- pkg/agent/agent.go
- pkg/agent/agent_test.go
- pkg/agent/provisioning_test.go
- pkg/cmd/cmd_test.go
- pkg/cmd/properties/properties.go
- pkg/cmd/root.go
- pkg/cmd/testdata/test_with_agent_cfg.yaml
- pkg/config/agentfeaturesconfig.go
- pkg/config/externalidpconfig.go
- pkg/config/externalidpconfig_test.go
ObjectSlicePropertyValues are now parsed when prefixed with the tag @Secret.
> APIGOV-29620 - parse object slice properties

- pkg/authz/oauth/constants.go
add const for wso2 grant types and any agents going forward that need to add grant types
> APIGOV-29494 - add const for wso2 grant types

- go.sum
- pkg/cmd/properties/properties.go
- pkg/config/centralconfig.go
- pkg/config/externalidpconfig_test.go
- pkg/config/resourcefilterconfig.go
- Add min/max item options for object array settings
- Allow watch filter on unscoped resources
> APIGOV-29833 - enhancements for support of traceable agent

- pkg/agent/handler/credential.go
- pkg/agent/handler/credential_test.go
- pkg/util/decrypt.go
- pkg/util/encrypt.go
- pkg/util/encrypt_test.go
- pkg/util/gcmencrypt.go
- Changes to support JWE encryption when message size is larger than the max message size based on the key type
> APIGOV-29884 - Encrypt credential data using JWE

- pkg/traceability/sampling/globalsampling.go
- create channel in all cases the sample objec is initialized
> APIGOV-30163 - initialize disable sampling channel in all global sampler

- pkg/transaction/eventreport.go
Stemming from code review on code already merged.
Refactor summary event code from nasty nested if statements.
> APIGOV-30995 - refactor nasty if else

- pkg/apic/servicebody.go
- pkg/apic/servicebuilder.go
- pkg/apic/servicebuilder_test.go
- pkg/apic/specoas2processor.go
- pkg/apic/specoas3processor.go
- pkg/apic/specparser.go
- pkg/apic/specparser_test.go
- pkg/apic/testdata/petstore-openapi3.json
- pkg/apic/testdata/petstore-swagger2.json
Adds strip extensions functionality to OAS2 and OAS3 and add a serviceBuilder option
> APIGOV-31247 - strip extensions
