pkg/util/util.go
@kflan-io @dfeldick @vivekschauhan @jcollins-axway 
Please review.  Changing the return to hostname so it only returns the host portion of the url
=> APIGOV-17281 - return hostname instead of string

pkg/apic/apiservice.go, pkg/apic/apiserviceinstance.go, pkg/apic/apiservicerevision.go, pkg/apic/client.go, pkg/apic/consumerinstance.go
Set resource version in PUTs for
apiservice
apiservicerevision
apiserviceinstance
consumerinstance
@vivekschauhan @jcollins-axway  I also updated resource version in client.  However, Vivek, jason and I was a part of a meeting with Seby, Chandan, and Ashutosh... talking about removing the xj-axway-agent env var.  Somehow they are seeing this being set multiple times past agent startup...  We are thinking at this point, we can remove this code.  We can discuss.
Along with that, do you think we need to update the following?
service.go
- line 262
- line 330
subscriptionschema.go
-line 170.
In these instances, we are doing a POST before doing a PUT.  I know you said maybe we need to do a GET on the object first...  what are your thoughts?  The above changes are necessary... what about the …
=> APIGOV-17949 - update resource version

errors.md, pkg/agent/discovery.go, pkg/apic/errors.go, pkg/apic/specoas2processor.go, pkg/apic/specoas3processor.go
@vivekschauhan @jcollins-axway @dfeldick @kflan-io please review
oas2 and oas3 require endpoint validation. 
oas2 - check to see if schemes are empty.  If empty try and create endpoint.  If endpoint cannot be created, throw error
oas3 - check to see if servers are empty.  If empty, throw an error
=> APIGOV-18001 - oas2 and oas3 endpoint validation

pkg/agent/awsagents.go, pkg/agent/edgeagents.go, pkg/agent/traceabilityagents.go
Currently none of the TA merge functions are propagating any resource configs.
Fill in AWS, edge and (base) TA agents
=> APIGOV-18153 - merge resources to cfg for TA

pkg/agent/discoverycache.go, pkg/apic/specoas2processor.go, pkg/config/logconfig.go
fix the following sonar issues
pkg/agent/discoverycache.go
Refactor this function to reduce its Cognitive Complexity from 17 to the 15 allowed.
pkg/apic/specoas2processor.go
Remove this redundant boolean literal
pkg/config/logconfig.go
Refactor this function to reduce its Cognitive Complexity from 20 to the 15 allowed.
=> APIGOV-18214 - sonar fixes

pkg/apic/consumerinstance.go, pkg/apic/definitions.go
Current valid policies {"verify-api-key", "pass-through", "verify-oauth-token"}
If policy is not valid, still allow the catalog asset to be created.  However, do not allow subscription.  Set auth policy and status on serviceBody.  Auth policy "pass-through" is not allowed subscriptions.
=> APIGOV-18147 - unidentified inbound policy

pkg/apic/auth/apicauth.go
Clean out expiry token.
then when get cached token is empty, try and fetch new token
=> APIGOV-18296 - clean out expiry token.  Fetch new

pkg/api/client.go
Set request Close to true.  For client requests, setting this field prevents re-use of TCP connections between requests to the same hosts
=> APIGOV-18327 - set req.Close to true

pkg/apic/apiserviceinstance.go, pkg/apic/apiservicerevision.go, pkg/apic/consumerinstance.go
Expose the real error from apiServiceDeployAPI.  Before this fix, the err was getting eaten and not returning.  Now, if apiServiceDeployAPI returns an err, we try to rollback.  
If addAPI && rollback returns an error, we concat rollback err and apiServiceDeployAPI  error and return that.  
If !addAPI or no error on rollback, we return the (real) apiServiceDeployAPI err.
=> INT-00000 - expose real error

pkg/config/centralconfig.go, pkg/config/centralconfig_test.go, pkg/transaction/eventgenerator_test.go, pkg/transaction/metric/metricscollector.go
Initializing start time to be minute behind for initial usage report generation
Added validation for event aggregation interval config
=> APIGOV-18754 - Initializing start time to be minute behind for initial usage report generation

pkg/agent/discovery_test.go, pkg/apic/client.go, pkg/apic/client_test.go
Prep work for dave's demo.  Created getter for platform user info and user name.
I made the getter for the platform info private.  But we can make it public and then let the calling function grab whatever they want from the user info.  
For now, i kept the email getter, created a user name getter and just make the get platform user info generic.
=> APIGOV-00000 - create getters for platform user info and user name

pkg/jobs/jobs.go, pkg/jobs/pool.go, pkg/traceability/sampling/sampling_test.go, pkg/transaction/eventgenerator.go, pkg/transaction/metric/definition.go, pkg/transaction/metric/metricscollector.go, pkg/transaction/metric/metricscollector_test.go, pkg/transaction/metric/metricspublisher.go
- Update to create publisher within collector
- Added publish queue to collector for events generated by collector
- Updates to publish events based on queue instead of channel and perform cleanup of counter on successful publish
- Updates to unregister job from global pool
- Update to expose metric collector by making GetMetricCollector API call
=> APIGOV-18737 - Changes to reset usage/metric counter on successful publish

pkg/traceability/traceability.go, pkg/transaction/eventgenerator.go, pkg/transaction/metric/cachestorage.go, pkg/transaction/metric/definition.go, pkg/transaction/metric/metricscollector.go, pkg/transaction/metric/metricscollector_test.go
- Changes to load cached usage/metric data on agent initialization
- Changes to update the counters/metric in cache as the registry is updated
- Added cache store job that triggers every 5 sec to store the data to disk
- Changes to reset the cached counter when the counters in registry are reset.
=> APIGOV-18347 - Added storage for usage/metric data

pkg/transaction/metric/definition.go, pkg/transaction/metric/metricscollector.go
Fix include:
- correctly formatting the time in usage report with ISO8601
- using the start time in the event report as key
=> APIGOV-18347 - Fix for reporting time format

errors.md, pkg/cmd/cmd_test.go, pkg/cmd/properties/properties.go, pkg/cmd/properties/resolver/secretResolver.go, pkg/cmd/root.go
- Changes to secure string based configuration by using reference of secret resource in Central
- Secret resolver gets hooked by in property parser for string flags and property
- Secret resolver parses the secret and key from the reference string value in config and gets the secret from API server
- The secret is cached to minimize the number of API calls to API server to fetch secret in case same secret is used for multiple config
- Also includes a fix to setup beats logger to allow logging any log entries during agent initialization
=> APIGOV-18029 - Changes to use secret reference in config

pkg/transaction/definitions.go, pkg/transaction/logeventbuilder.go, pkg/transaction/logeventbuilder_test.go
Update the struct to for ID and Version to match definitions.json
"product": {
"type": "object",
"description": "Descriptor of the product",
"properties": {
"id": {
"type": "string",
"description": "Product id"
},
"version": {
"type": "string",
"description": "Product version"
}
},
"required": [
"id"
]
},
=> APIGOV-19050 - Update product struct for ID and Version

pkg/traceability/traceability.go, pkg/traceability/traceability_test.go
Because the jobs interface does not currently do retries and eventually fail, it does not function as a healthchecker the way the other healthcheckers do... it does not terminate the agent when there is an error. So, in order to temporarily make the agent fail on startup as expected if there is an error, I implemented both a healthchecker Job (the way we want to move to in the future) and an "old-style" healthchecker, which in the future (marked by TODO comments) will be removed.
=> Apigov - 19048 - add back temporary "old" healthchecker

pkg/traceability/traceability.go, pkg/transaction/metric/metricscollector.go
The following logs have been updated
traceability
where %d is the number
1. "Creating %d transaction events"
2. "%d events have been published"
3. "Failed to publish transaction event : "
metrics and usage
1. "Creating usage event with %d transactions"
2. "Published usage report [start timestamp: %d, end timestamp: %d]"
3. "Failed to publish usage event : "
=> APIGOV-19413 - update trans and metrics/usage events

pkg/agent/discovery.go, pkg/agent/statusupdate.go, pkg/agent/util.go, pkg/traceability/traceability.go
1. Checks are run based on -> CENTRAL_REPORTACTIVITYFREQUENCY
2. When frequency hits, update last activity time for agent resource (and ultimately UI)
3. Only report CENTRAL_REPORTACTIVITYFREQUENCY for periodic checks.  Filter on periodic and not immediate.  Immediate only used for agent status 
4. Refactor time since only periodic status uses it
=> APIGOV-19572 - report last activity based on activity frequency

pkg/apic/client.go, pkg/apic/consumerinstance.go, pkg/apic/definitions.go, pkg/apic/mockserviceclient.go, pkg/apic/subscriptionschema.go, pkg/apic/subscriptionschema_test.go, pkg/apic/subscriptionschemabuilder_test.go, pkg/util/healthcheck/healthchecker.go
- Updates the subscription schema registration logic to use a local cache to identify if the schema requires updates.
- The subscription schema is retrieved on startup using GET call and stored in local cache
- On update lookup is done against the local cached if subscription schema requires update.
- When POST or PUT calls are placed for creating/updating the subscription schema, the schema is added to the local cache
=> APIGOV-19570 - Limiting the calls for subscription schema updates 

pkg/agent/agent.go, pkg/agent/discovery_test.go, pkg/agent/discoverycache.go, pkg/agent/statusupdate.go, pkg/apic/apiserver/models/api/v1/time.go, pkg/apic/client.go, pkg/apic/definitions.go, pkg/apic/resourcePagination.go, pkg/apic/subscriptionmanager.go, pkg/cmd/agentversionjob.go, pkg/jobs/baseJob.go, pkg/jobs/definitions.go, pkg/jobs/detachedintervaljob.go, pkg/jobs/intervaljob.go, pkg/jobs/jobs.go, pkg/jobs/pool.go, pkg/jobs/pool_test.go, pkg/jobs/retryjob.go, pkg/jobs/scheduledjob.go, pkg/traceability/traceability.go, pkg/transaction/metric/metricscollector.go
- Added ability to set page size when using api server paging methods
- Set page size for discovery cache to 100
- removed query filter on discovery cache and check locally for externalapiid attr
- getting api service instances in place of consumer instances
-- using cache to check for apis removed on dataplane
- only querying for new services and instances, hourly querying for all services and instances
- backoff implemented in jobs api
Note: not using the attribute on the agent resource, replaced with the timestamp query
=> APIGOV-19648 - jobs and discovery cache performance changes

pkg/apic/apiserver/models/api/v1/resourcemeta.go
The lack of finalizers json tags makes them un-editable. The inclusion of omitempty on the maps (attributes, tags, finalizers) makes them add only which isn't what's required.
=> Include json tags for finalizers and remove omitempty

pkg/apic/apiservicerevision.go, pkg/apic/service.go, pkg/config/subscriptionconfig.go, pkg/notify/definitions.go, pkg/notify/subscriptionnotification.go, pkg/notify/subscriptionnotification_test.go, pkg/notify/template/emailtemplate.go
1. refactor code for apiservicerevision title
2. use the go template
3. take advantage of 3 more date formats
=> APIGOV-19751 - use go template for apiservicerevision title and email notification

pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/apic/consumerinstance.go, pkg/apic/errors.go
1) fix error message if no default team is provided
2) fix init problems causing merged resource values to be overwritten by config values
=> APIGOV-19886 - fix init problem causing AgentResource values to not be merged

pkg/config/subscriptionconfig.go, pkg/notify/subscriptionnotification.go, pkg/notify/template/emailtemplate.go
Allow the customer to configure {{.AuthTemplate}} 
1.  this is an alternate solution for {{if}} / {{else}}
2.  this automatically pulls in the auth type. If it doesn't exist in the env_var, it will use the default.
=> APIGOV-20279 - verify if email body is using {{.AuthTemplate}}

docs/utilities/index.md, pkg/agent/statusupdate.go, pkg/apic/apiservicerevision.go, pkg/apic/client.go, pkg/apic/consumerinstance.go, pkg/apic/resourcePagination.go, pkg/apic/subscriptionmanager.go, pkg/cmd/root.go, pkg/config/subscriptionconfig.go, pkg/config/webhookconfig.go, pkg/util/healthcheck/healthchecker.go
Based on the ambiguity of debug vs trace and what customers want or need to see, this is about the extent I want to go for right now. Just move some of the messages that are clearly pretty low-level. If there are no objections and this is approved, I will take a similar approach to the agents. If you feel that it's gone overboard, let me know also.
=> APIGOV-19801 - change some debug logs to trace

Makefile, go.sum, pkg/agent/agent.go, pkg/apic/client.go, pkg/jobs/pool.go, pkg/transaction/logeventbuilder.go, pkg/transaction/metric/cachestorage.go, pkg/transaction/metric/metricscollector.go, pkg/transaction/metric/offlinereport.go, pkg/util/util.go
- moved IsNotTest from agent to util for more global availability
- called IsNotTest to prevent healthcheck startup during tests, which caused race conditions for tests
- lock poolStatus get/set, which were flagged as race conditions in tests
=> APIGOV-20509 - fix race conditions

pkg/transaction/util.go, pkg/transaction/util_test.go
Give functions for HTTP status better names and deprecate old ones. These new functions will be called from various trace agents.
=> APIGOV-20628 - refactor function names

pkg/traceability/config.go, pkg/traceability/traceability.go, pkg/transaction/definitions.go, pkg/transaction/eventgenerator.go, pkg/transaction/httpprotocolbuilder.go, pkg/transaction/httpprotocolbuilder_test.go, pkg/transaction/logeventbuilder.go, pkg/transaction/logeventbuilder_test.go
1. new traceability configuration - apiExceptionsList: ${TRACEABILITY_EXCEPTION_LIST:"stringPath1, stringPath2, etc"}
2. Before redaction on URI, check to see if api path matches with entries in apiExceptionsList
3. If we find a match, do not send the event through
4. Should not affect go right path
5. Create debug logs to show what api path sdk found to ignore
6. Fix lint warning about upper case error verbiage(s)
=> APIGOV-20614 - create an traceability api (path) exceptions list

go.mod, pkg/agent/statusupdate.go, pkg/apic/subscriptionmanager.go, pkg/cmd/root.go, pkg/config/centralconfig.go, pkg/config/logconfig.go, pkg/jobs/README.md, pkg/jobs/backoff.go, pkg/jobs/backoff_test.go, pkg/jobs/baseJob.go, pkg/jobs/basejob_test.go, pkg/jobs/channeljob.go, pkg/jobs/channeljob_test.go, pkg/jobs/definitions.go, pkg/jobs/detachedintervaljob.go, pkg/jobs/intervaljob.go, pkg/jobs/jobs.go, pkg/jobs/pool.go, pkg/jobs/pool_test.go, pkg/jobs/retryjob.go, pkg/jobs/retryjob_test.go, pkg/jobs/scheduledjob.go
- added a channel job type, only excepts a stop channel
- added a timeout for a job execution, still needs a configuration for this
- fixed issue of creating status update jobs when no agent name provided
- added backoff timer for calling the job ready function 
- attribute on job to know when it is ready
- on stop call kill the ready loop or the running loop
- only initialize one version checker job
=> APIGOV-21016 - updates for the jobs library

pkg/apic/consumerinstance.go, pkg/apic/definitions.go, pkg/apic/service_test.go, pkg/apic/servicebody.go, pkg/apic/servicebuilder.go, pkg/apic/specoas2processor.go, pkg/apic/specoas3processor.go, pkg/apic/specparser.go, pkg/notify/subscriptionnotification.go, pkg/notify/template/emailtemplate.go
- add auth policy and key info parsing to oas2 and oas3 spec parser
- add key location for api key auth in notification message
- add getters to retrieve the auth info or key info from the service body
=> APIGOV-21244 - updates for spec parsing and subscription notifications

build/scripts/sonar.sh, errors.md, pkg/agent/resource/manager.go, pkg/agent/stream/client.go, pkg/api/client.go, pkg/watchmanager/harvesterclient.go, pkg/watchmanager/manager.go, pkg/watchmanager/options.go, pkg/watchmanager/proxy.go, pkg/watchmanager/proxy_test.go
- Added a custom dialer for gRPC connection to proxy.
- The dialer uses the configured proxy URL to establishes the connection and send CONNECT request to proxy
- Includes a fix to use insecure TLS connection to watch controller
- Includes a fix in API client to use proxy with no TLS configg
=> APIGOV-21298 - Proxy support for gRPC watch and harvester connections

pkg/agent/agent.go, pkg/agent/handler/handlers.go, pkg/agent/handler/handlers_test.go, pkg/agent/stream/eventlistener.go, pkg/agent/stream/eventlistener_test.go, pkg/agent/stream/watchtopic.go
- Added methods to allow agent implementation to register/unregister event handlers
- Added Proxy resource handler to invoke registered event handlers. Proxy handler gets registered to event listener during the agent initialization, this allows agent implementation to register event handlers when needed(before agent initialization or while agent is running)
- Updates to pass event metadata to handlers
=> APIGOV-21351 - Support for registering event handlers

pkg/agent/agent.go, pkg/agent/cache/manager.go, pkg/agent/discovery_test.go, pkg/agent/instancevalidator.go, pkg/agent/instancevalidator_test.go, pkg/agent/resource/manager_test.go, pkg/agent/teamcache.go, pkg/agent/teamcache_test.go, pkg/apic/apiservice.go, pkg/apic/apiservice_test.go, pkg/apic/apiserviceinstance.go, pkg/apic/client.go, pkg/apic/client_test.go, pkg/apic/consumerinstance.go, pkg/apic/definitions.go, pkg/apic/definitions/definitions.go, pkg/apic/mockserviceclient.go, pkg/apic/service.go
- Add the cacheManager to the ServiceClient
- Add the team cache to the cacheManager
- Remove calls for resources by attributes
- Look for resources in local cache
=> APIGOV-21493 Retrieve resources from cache instead of making requests for resources by attributes

docs/discovery/index.md, pkg/agent/cache/manager.go, pkg/agent/stream/client.go, pkg/agent/stream/client_test.go, pkg/config/agentfeaturesconfig.go, pkg/config/agentfeaturesconfig_test.go, pkg/config/centralconfig.go, pkg/watchmanager/manager.go
- Added callback on watch manager to be invoked after successful registration and processing harvested events
- Added methods to cache manager to acquire and release lock for read on api-server resource caches
- Updated streaming client to lock the resource cache for read and release the lock by setting up the callback on watch manager
- Reduced the default interval to persist cache to 10s
- Setting the default for persist cache agent feature to false for disabling the persisted cache by default even in gRPC mode. The feature can be enabled by setting the AGENTFEATURES_PERSISTCACHE config to true
=> APIGOV-21601 - Fix for processing watch event before discovery

pkg/agent/agent.go, pkg/agent/discovery.go, pkg/agent/discoverycache.go, pkg/agent/instancevalidator.go, pkg/agent/instancevalidator_test.go, pkg/apic/apiserviceinstance.go, pkg/apic/service.go
- Added RegisterServiceValidator method to allow agents to setup callback for validating if the service exists on dataplane.
- The SDK calls the service validator to check if the API service associated to the API on dataplane needs to be deleted
=> APIGOV-21642 - Updates for API service/instance deletion

pkg/apic/apiservice.go, pkg/apic/apiserviceinstance.go, pkg/apic/apiservicerevision.go, pkg/apic/consumerinstance.go, pkg/migrate/attributemigration.go
- Changes to update only x-agent-details subresource rather than placing PUT call for all existing subresources on published resources.
- For APIService status is included for subresource updates on discovered APIServices
=> APIGOV-22010 - Fix for updating agent specific subresources

pkg/agent/resource/governanceagents.go, pkg/cmd/root.go
To make the Governance Agent for Amplify Gateway seperate from Traceability agent, 
the logs level should be standard ones (not harcoded any more)
and revert the mix of Gov Agent with Traceability.
=> Ampgw 615 - Split Traceability agent from Governance agent.

pkg/apic/subscription.go
1. validate length of description > 350
2. if greater, warn that we are truncating
3. send in truncated description
=> APIGOV-02468 - validate subscription state description

pkg/transaction/metric/cachestorage.go, pkg/transaction/metric/definition.go, pkg/transaction/metric/metricbatch.go, pkg/transaction/metric/metricscollector.go, pkg/transaction/metric/metricscollector_test.go
- Combine the provider and consumer subscription/application metric event
- Restructure data in metric event to have separate sections for subscription, application and api
- Combine the api and subscription/application metric to single event of type "api.transaction.status.metric"
=> APIGOV-21522 - Changes based on feedback

pkg/agent/discoverycache.go, pkg/agent/handler/accessrequest.go, pkg/agent/handler/accessrequest_test.go, pkg/agent/provisioning.go, pkg/apic/provisioning/accessrequest.go, pkg/apic/provisioning/mock/provisioning.go
- In provisioning/accessrequest.go, add a method for retrieving instance details
- Remove GetAPIID() and GetAPIStage() methods from access request interface
=> APIGOV-22216 Add method to AccessRequest interface to expose instance details

build/scripts/promote.sh
Until we can push directly to main, I commented out the commit/push from the script. In it's place, I added echo statements to instruct the user exactly what to manually do to complete the release.
=> APIGOV-00002 - disable commit/push of version file for now

pkg/agent/accesscontrollisthandler.go, pkg/agent/discovery_test.go, pkg/agent/provisioning.go, pkg/agent/provisioning_test.go, pkg/apic/apiservice.go, pkg/apic/apiservice_test.go, pkg/apic/client.go, pkg/apic/client_test.go, pkg/apic/mock/mockclient.go, pkg/apic/provisioning/accessrequestdefinitionbuilder.go, pkg/apic/provisioning/credentialrequestdefinitionbuilder.go, pkg/apic/service.go, pkg/apic/servicebody.go, pkg/util/util.go
- update how the hash is set on the cred and access request defs
- combine CreateSubResourceScoped and CreateSubResourceUnscoped logic to single method that now returns the data from the last updated sub resource call
- fix use of updateOrCreateResource method to check if hash on central matches hash in resource sent in before updating it and its sub resources
- merge subresources from resource on central and subresources to be updated
=> APIGOV-22609 - fix updating of resources and sub resources based on spec hash

pkg/transaction/metric/metricscollector.go
- Changes to setup app bucket key with the ID of managed app or catalog app. Previously the managedapp metdata.id was being used however the serialized event contained the catalog app id and dues to this the entries from the app bucket were not getting cleaned up correctly
=> APIGOV-23080 - Fix for setting app bucket identifier

pkg/agent/cache/apiserviceinstance.go, pkg/agent/cache/manager.go, pkg/agent/eventsync.go, pkg/apic/apiservice.go, pkg/apic/apiservice_test.go, pkg/apic/apiserviceinstance.go, pkg/apic/client.go, pkg/apic/definitions/definitions.go, pkg/apic/util.go, pkg/cmd/cmd_test.go, pkg/config/centralconfig.go, pkg/config/migrationconfig.go, pkg/config/migrationconfig_test.go, pkg/migrate/apisimigration.go, pkg/migrate/apisimigration_test.go, pkg/migrate/ardmigration.go, pkg/migrate/ardmigration_test.go, pkg/migrate/attributemigration.go, pkg/migrate/attributemigration_test.go, pkg/migrate/marketplacemigration.go, pkg/migrate/marketplacemigration_test.go, pkg/migrate/migration.go
- Only create 1 api service instance per stage, update it to point to latest revision
- Migration code to clean old instances, all but latest one per stage, within a service
- Config option to enable the migration, default off
=> APIGOV-22850 - one api service instance per stage

pkg/cmd/cmd_test.go, pkg/cmd/properties/properties.go
1.  Add new options WithXXXLimit to func AddDurationProperty.  It takes a lower limit and upper limit time.Duration range
2. When implemented, a duration property will contain a lower limit and upper limit function.  It will only be added as a property if the lower limit is less than the upper limit.  And neither of the limits are zero.  When added, new property name and flags will be created for this range
3. DOES not remove logic for - qaEnforceDurationLowerLimit = "QA_ENFORCE_DURATION_LOWER_LIMIT"
4. Validation checks to see if the user entered config is between range
5. If it is, NOP
6. If it is not, then warn user that the set config is not within range and pick up DEFAULT setting
7. Update tests (to check warning).  Function does not return error
=> APIGOV-23227 - allow implementer the option of setting a lower and upper limit range for a configuration

pkg/agent/agent.go, pkg/agent/cache/accessrequest.go, pkg/agent/cache/accessrequest_test.go, pkg/agent/cache/manager.go, pkg/agent/cache/watchresource.go, pkg/agent/cache/watchresource_test.go, pkg/agent/events/watchtopic.go, pkg/agent/events/watchtopic_test.go, pkg/agent/eventsync.go, pkg/agent/handler/accessrequest.go, pkg/agent/handler/accessrequest_test.go, pkg/agent/handler/traceaccessrequest_test.go, pkg/agent/handler/watchresource.go, pkg/agent/handler/watchresource_test.go, pkg/config/centralconfig.go, pkg/config/resourcefilterconfig.go, pkg/transaction/metric/metricscollector.go, pkg/transaction/metric/metricscollector_test.go
- Updates to setup custom watch filters in central config
- Changes to create/update watch topic with custom filters in addition to the agent type filters
- Create a custom watch resource handler to cache watch resources matching the custom filter
- Updated cache manager to store custom watch filter resources
- Fix to lookup reference for APIServiceInstance in AccessRequest
- Fix in metric collector to address external API IDs with dot characters which caused issues with bucket lookup while processing metrics.
=> APIGOV-23150 - Changes to create/update watch topic with custom filters 

errors.md, pkg/apic/errors.go, pkg/traceability/sampling/globalsampling.go, pkg/util/errors/errors.go, pkg/util/healthcheck/error.go
1. Check that error var is being used in md
2. Check that error var is in code
3. Check that error code exists in docs.axway tips-troubleshooting-mitigation pages
4. If error var wasn't being used in code, remove from md and equivalent pages in docs.axway
related ticket for docs.axway - https://jira.axway.com/browse/APIGOV-23248
=> APIGOV-21483 - sync error codes with documentation

pkg/cmd/properties/properties.go
I could have just removed the trace statement.
But, put quick checks to see if a floor and ceiling was created for the duration range.  If yeah, then display trace... and return true.
If it's overkill, i'll revert and remove the trace statement.
=> APIGOV-11111 - justify displaying trace if range duration is set

pkg/agent/eventsync.go, pkg/agent/instancevalidator.go, pkg/apic/apiserviceinstance.go, pkg/apic/client.go, pkg/apic/definitions.go, pkg/apic/mock/mockclient.go, pkg/apic/service.go, pkg/migrate/instancemigration.go
- Remove finalizers on existing instances
- Do not add a finalizer to new instances
=> APIGOV-23402 migrate api service instances to remove finalizers

pkg/agent/provisioning.go, pkg/migrate/marketplacemigration.go
Do not attempt to migrate marketplace provisioning, if marketplace provision migration had previously taken place.  When marketplace provision migration is complete x-agent-details marketplace migration should read complete
1. Moved check for migration completion to its own func
2. Call specific check to apiservice, to validate if marketplace migration has already completed
3. If not, run migration on the apiserviceinstance
4. If already migrated, skip migrationfor that apiserviceinstance
For the life of me, I have no idea this was still failing.  Could have sworn it was working... 
Tested
1. start with non MP v7 agent
2. discover APIs
3. apis have no migration ran on them for marketplace
4. add MP configs and start v7 agent
5. already discovered APIs ran through marketplace migration
6. …
=> APIGOV-23428 - check migration complete

pkg/agent/aclupdatejob_test.go, pkg/agent/agent.go, pkg/agent/cache/accessrequest_test.go, pkg/agent/cache/apiservice.go, pkg/agent/cache/apiserviceinstance.go, pkg/agent/cache/manager.go, pkg/agent/cache/manager_test.go, pkg/agent/discovery.go, pkg/agent/errors.go, pkg/agent/instancevalidator.go, pkg/agent/instancevalidator_test.go, pkg/agent/provisioning.go, pkg/agent/teamcache_test.go, pkg/api/mockhttpclient.go, pkg/apic/apiservice.go, pkg/apic/apiservice_test.go, pkg/apic/apiserviceinstance.go
- After validating instances validate services have at least 1 instance
- Update cache to track instance count in services
- Add more tests for coverage in cache package
- Add wait groups so validator and publishing do not run at the same time
- Remove code that cleans AccessRequests during publishing, no longer needed
- Move API Service cache update to apic package, service added to cache before instance
- Add API Service name as secondary key
- Remove extra call to update agent details of service instance
=> APIGOV-23450 - remove services with 0 instances

pkg/apic/provisioning/mock/provisioning.go
update mock form credential request getName() to return credential name
=> APIGOV-23394 - add GetName() to mock

pkg/agent/cache/apiservice.go, pkg/agent/cache/apiserviceinstance.go, pkg/agent/cache/manager.go, pkg/agent/cache/manager_test.go
- Fix persistent cache to correctly save instance count to disk
- When a new service is added to the cache check to see if any instances linking to that service exist in cache
=> APIGOV-23542 - fixes for instance counting agains services in cache

pkg/agent/agent.go, pkg/agent/discovery.go, pkg/agent/eventsjob.go, pkg/agent/eventsync.go, pkg/agent/hcjob.go, pkg/agent/instancevalidator.go, pkg/agent/poller/options.go, pkg/agent/statusupdate.go, pkg/agent/stream/client.go, pkg/agent/stream/client_test.go, pkg/agent/stream/options.go, pkg/apic/subscriptionmanager.go, pkg/jobs/backoff.go, pkg/jobs/backoff_test.go, pkg/jobs/baseJob.go, pkg/jobs/channeljob.go, pkg/jobs/intervaljob.go, pkg/jobs/jobs.go, pkg/jobs/pool.go, pkg/jobs/retryjob.go, pkg/jobs/scheduledjob.go, pkg/util/healthcheck/definitions.go, pkg/util/healthcheck/healthchecker.go, pkg/util/healthcheck/periodichealthcheck.go, pkg/util/util.go, pkg/watchmanager/client.go, pkg/watchmanager/manager.go
- Changes to increase the retry interval for watch client connection
- Changes to update the agent status with the healthcheck failure message
- Change to reset the backoff interval for job pool to initial interval when current interval exceeds max
- Fix in watch client to report healthcheck failure on initial connection error
- Fix in stream client to register central healthcheck on initial connection failure
=> APIGOV-23312 - Changes to report error message on unhealthy status

pkg/agent/discoverycache.go
In testing migration the discovered func (called by go routines) were not being called in the order it needed to be.  Refactored execution by removing go routines and calling functions explicitly
=> APIGOV-23709 - directly execuate discovered functions

pkg/agent/cache/apiservice.go, pkg/agent/cache/apiserviceinstance.go, pkg/agent/discoverycache.go
Possible pitfalls where logging could be used for instance validation deleting apiservice when it's not supposed to
=> APIGOV-23714 - add logging for QAA

pkg/agent/handler/credential.go, pkg/agent/handler/credential_test.go, pkg/apic/provisioning/credentialrequest.go, pkg/apic/provisioning/mock/provisioning.go
- updated credential provisioning mock for idp credential data and CRD data
=> APIGOV-23681 - Changes to pass CRD data to provisioning handler

pkg/agent/provisioning.go
1. remove check to agent details from provisioning.  Leave the check only in the marketplacemigration
2. Only run migration if the resource instance doesn't exist.  If it does exist, we know that migration has already ran
=> APIGOV-23745 - update migration in provisioning part only

pkg/transaction/metric/metricscollector.go
The beat library allows the following sub commands to be used
- traceability-agent.exe run --N
- traceability-agent.exe export template
- traceability-agent.exe export config
- traceability-agent.exe keystore list
Unfortunately, we have little control over these subcommands, as far as I can see.  I don't see a way to suppress them at this time.  So, instead of attacking it on that end, I decided to handle the nil pointer on the create metrics side.  With this change, it at least gets to the beats subcommand and executes them correctly.
Tested this and now these subcommands show successfully.
=> APIGOV-23866 - check for nil

pkg/agent/handler/accessrequest.go, pkg/agent/handler/accessrequest_test.go, pkg/apic/apiservice.go, pkg/apic/apiserviceinstance.go, pkg/apic/servicebody.go, pkg/apic/servicebuilder.go, pkg/apic/servicebuilder_test.go
1.  First discover only published proxies, ignoring unpublished
2.  Cycle through all unpublished proxies and if the ID is found in the cache, meaning it had been published, update the instance of the API that has an AccessRequestDefinition/CredentialRequestDefininition attached (to be removed), not able to be subscribed to.
3.  Ignore all other unpublished APIs
4.  Continue the grouping by the primary key and the revision logic for multiple proxies with the same primary key as we do today (NOTE : on the v7 side, we are not formatting the logical key with 'vhost')
Additionally the handling of an access request should check the status of the front end proxy, if it is unpublished the returned error for display in the UI should be friendly. (ex. Access can not be granted at this time, the …
=> APIGOV-24232 - updates on processing of services in an Unpublished state

pkg/agent/poller/poller.go, pkg/harvester/harvesterclient.go, pkg/watchmanager/manager.go, samples/watchclient/pkg/client/client.go
- Changes to process 410 response from harvester and use the sequence to watch for following events.
- Fix in watch manager to initialize with no sequence
=> APIGOV-24414 - Updated harvester client to manage purged sequences 

pkg/agent/eventsync.go
- Fix to not update the sequence manager when no events are returned by harvester for a new watchtopic created by the agent during the initialization of the cache when persistence cache is disabled
=> APIGOV-24763 - fix to initialize current sequence for a new watch

pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/config/usagereportingconfig_test.go
No longer have SDK annotate environment of agents running on the Environment, this will be handled on the SaaS side.
=> APIGOV-24074 - remove notating env of agent

pkg/apic/apiserver/models/api/v1/owner.go, pkg/transaction/eventgenerator.go, pkg/transaction/metric/definition.go, pkg/transaction/metric/metricscollector.go, pkg/transaction/metric/metricscollector_test.go, pkg/transaction/models/definitions.go
- fix missing organization id in owner marshal/unmarshal
- use same structs for matching data in transaction and metrics
=> APIGOV-25440 - updates for api transaction and metric defs

pkg/util/healthcheck/definitions.go, pkg/util/healthcheck/healthcheck_test.go, pkg/util/healthcheck/healthchecker.go
- Improvement to remove the call for executing the registered healthchecks when processing the status request
=> APIGOV-25722 - remove the call to execute healthchecks for the status request processing

pkg/agent/agent.go, pkg/apic/service.go, pkg/authz/oauth/authclient.go, pkg/authz/oauth/authclient_test.go, pkg/authz/oauth/clientsecretauthenticator.go, pkg/authz/oauth/constants.go, pkg/authz/oauth/provider.go, pkg/config/externalidpconfig.go, pkg/config/tlsconfig.go
- Updated IDP configuration to setup root CA certificate, client certificate and client key to be used for setting up mTLS connection to IdP
- Updated IDP configuration to setup scope for requesting token
- Updated client secret authenticator to include scope while requesting the token from IdP
- Updated provider auth client to use the TLS config from IdP config if provided otherwise use the Central TLS config
=> APIGOV-24403 - Support for requesting token with scope and mTLS connection with IdP

pkg/authz/oauth/authclient.go, pkg/authz/oauth/provider.go, pkg/config/externalidpconfig.go
- Added config AGENTFEATURES_IDP_AUTH_USECACHEDTOKEN_1 to setup the IdP OAuth client to use cached token
- Config can be set to "false" if cached token is not intended to be used while IdP client calls the DCR endpoints
=> APIGOV-26157 - Changes to configure the use of cached token for IdP OAuth client

pkg/traceability/redaction/redaction.go, pkg/traceability/redaction/redaction_test.go, pkg/transaction/httpprotocolbuilder.go
- Removed global variable to allow using the configured masking character
- Included fix for redacting request headers
=> APIGOV-26088 - Fix to use the masking character from config

CODEOWNERS, pkg/cmd/root.go, pkg/cmd/service/cmd.go, pkg/cmd/service/daemon/daemon.go, pkg/cmd/service/daemon/daemonlinux.go, pkg/cmd/service/daemon/daemonlinuxsystemd.go, pkg/cmd/service/service.go, pkg/cmd/service/service_test.go
1. add installDir parameter on command
2. when installDir added, set to WorkingDirectory in service definition
3. when installDir is not added, set to default execution path
=> APIGOV-26670 - add flag for installDir to be part of the install 

pkg/agent/agent.go, pkg/transaction/metric/metricscollector.go, pkg/transaction/metric/metricspublisher.go
- Allow a shutdown handler to be registered
- Call handler prior to exit of agent
- Add new interface on metric collector to push any cached metrics and usages
=> APIGOV-26694 - shutdown handler registration

pkg/traceability/config.go, pkg/traceability/sampling/definitions.go, pkg/traceability/sampling/errors.go, pkg/traceability/sampling/globalsampling.go, pkg/traceability/sampling/sampling_test.go
New updates for SDK
1. with no value to config, sampling percentage should default to 1
2. with value greater than 10, it should warn you that the agent will default to 1% and continue
3. removed json validation out of beats and manually validating sampling percentage
=> APIGOV-27057 - update sampling percentage with new default and max

pkg/agent/resource/manager.go
- Change to skip subresource update  other than status and x-agent-details during agent status updates
=> APIGOV-27099 - Update only status and x-agent-details 

pkg/agent/agent.go, pkg/agent/discoverycache.go, pkg/agent/handler/apiservice.go, pkg/agent/handler/apiservice_test.go, pkg/agent/handler/credentialrequestdefinition_test.go, pkg/agent/handler/environment.go, pkg/agent/handler/environment_test.go, pkg/agent/handler/instance.go, pkg/agent/handler/instance_test.go, pkg/agent/resource/manager.go
- Exclude processing events for agent specific resources(APIService, instance etc) from different environment
- Fix to keep the x-agent-details on agent status update
=> INT - Updates to exclude processing events on resources from other env

pkg/apic/apiservice.go, pkg/apic/apiservice_test.go, pkg/apic/apiserviceinstance.go, pkg/apic/apiserviceinstance_test.go, pkg/apic/definitions.go, pkg/apic/service.go, pkg/apic/servicebody.go, pkg/apic/servicebuilder.go, pkg/apic/servicebuilder_test.go, pkg/apic/testdata/existingserviceinstances.json
- Added interface to be used by agents for setting source dataplane type, if not set defaults to Unidentified
- Added interface to be used by graylog agent for setting referenced service and instance
- Updated APIService and APIServiceInstance processing to setup source subresource if not already set
- Source subresource is updated only when dataplane type or references require update.
=> APIGOV-27487 - Updates to setup source dataplane type and references

pkg/api/client.go, pkg/apic/apiservicerevision.go, pkg/apic/client.go, pkg/apic/client_test.go, pkg/apic/mock/mockclient.go, pkg/compliance/compliance_test.go, pkg/compliance/job.go, pkg/compliance/manager.go, pkg/compliance/runtimeresults.go
- Added support to execute PATCH request for sub resource updates
- Added compliance manager to register the job with configured processor to collect runtime results
- Compliance job collects the runtime results and execute patch request to update compliance property in source sub-resource on APIServiceInstance
=> APIGOV-27489 - processing runtime compliance

pkg/apic/apiserver/models/management/v1alpha1/model_dataplane_spec_azure.go
add mode to the azure dataplane.
Mode is either APIM or EventHub.  APIM is the default
=> APIGOV-28400 - add mode to azure dataplane

pkg/apic/definitions.go, pkg/apic/servicebody.go, pkg/apic/servicebuilder.go, pkg/apic/servicebuilder_test.go
Adds a flag that ignores creating ARD and CRDs based on the spec provided in the serviceBody
=> APIGOV-DG000 - fix ARD creation

pkg/agent/handler/credential.go, pkg/apic/provisioning/definitions.go
- adds an interface with which the agent can send what CRDs to ignore handling
=> APIGOV-29053 - support skipping handling external CRDs

pkg/util/dialer.go, pkg/watchmanager/manager.go
- With the upgrade of the gRPC library and replacing the deprecated methods to create client connections, the gRPC library uses the dns resolver to get the IP address of for the host on the machine where the client connection is initiated. 
- Override the resolver to allow the custom dialers used for connection via single entry and proxy
=> APIGOV-29235 - override resolver for gRPC

pkg/cmd/agentversionjob.go
- Removes jfrog call and uses the agentstate from the DA/TA resource(which are updated by separate jobs(for on-prem) and agents-controller(for SaaS)
- in case the state is not found, we simply log a warning with it(this can happen the first time the agent starts)
=> APIGOV-28932 - remove jfrog call and use agentstate

pkg/watchmanager/manager.go
- Use host name as scheme for gRPC resolver as library parses the address and uses the host as scheme to lookup the resolver
=> APIGOV-29316 - fix connection error over proxy

pkg/agent/discoverycache.go, pkg/agent/discoverycache_test.go, pkg/agent/handler/accessrequest.go, pkg/agent/handler/accessrequest_test.go, pkg/agent/handler/credential.go, pkg/agent/handler/managedapplicationprofile.go, pkg/agent/handler/managedapplicationprofile_test.go, pkg/apic/provisioning/mock/provisioning.go, pkg/apic/provisioning/propertybuilder.go, pkg/apic/provisioning/propertybuilder_test.go, pkg/apic/provisioning/schemabuilder.go, pkg/apic/provisioning/schemabuilder_test.go
- Add new builder method for adding enum labels and values
- Update provisioning to map selected label in request to mapped value
- Create mock type for app profile def testing
=> APIGOV-29633 - updates for application profile provisioning

pkg/agent/stream/client.go, pkg/watchmanager/client.go
- update to write initial request without relying on the initial timer
- include watchTopicSelf link in status update request to watch service
=> APIGOV-29690 - write initial watch request

pkg/apic/apiserver/models/management/v1alpha1/APIServiceInstance.go, pkg/apic/apiserver/models/management/v1alpha1/model_dataplane_spec_aws.go, pkg/apic/apiserviceinstance.go, pkg/apic/apiserviceinstance_test.go, pkg/apic/servicebody.go, pkg/apic/servicebuilder.go, pkg/apic/servicebuilder_test.go, scripts/apiserver/modify_models.sh
- Regenerated model with config for AWS Dataplane Setting with stageTagName property
- Updated APIServiceInstance model to use lifecyle as pointer
- Updated ServiceBodyBuilder to set instance lifecycle stage
=> APIGOV-29767 - Support for Stage mapping

pkg/agent/handler/accessrequest.go, pkg/agent/handler/accessrequest_test.go, pkg/agent/handler/credential_test.go, pkg/agent/handler/handler.go, pkg/apic/apiserver/models/management/v1alpha1/model_access_request_spec.go, pkg/apic/provisioning/accessrequest.go, pkg/apic/provisioning/accessrequestdefinitionbuilder.go, pkg/apic/provisioning/accessrequestdefinitionbuilder_test.go, scripts/apiserver/model_access_request_spec.tmpl
- Updated AccessRequestDefinitionBuilder to build ARD with transferable policy
- Updated AccessRequest handler to not cache created/updated access request until processed for pending state
- Updated access data to be passed to agent handler to hold referenced access request and its agent details
- On successful processing of migrated access request, referenced access request finalizer are removed and resource is deleted.
=> APIGOV-24309 - Support for processing access req transfer

pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/agent/credendtialvalidator.go, pkg/agent/events/requestqueue_test.go, pkg/agent/events/watchtopic.go, pkg/agent/events/watchtopic_test.go, pkg/agent/eventsync.go, pkg/agent/handler/agentresource.go, pkg/agent/handler/agentresource_test.go, pkg/agent/handler/watchresource.go, pkg/agent/handler/watchresource_test.go, pkg/agent/resource/complianceagents.go, pkg/agent/resource/discoveryagents.go, pkg/agent/resource/manager.go, pkg/agent/resource/manager_test.go, pkg/agent/resource/traceabilityagents.go, pkg/apic/definitions/definitions.go, pkg/cmd/cmd_test.go, pkg/cmd/root.go, pkg/config/centralconfig.go, pkg/config/centralconfig_test.go, pkg/config/logconfig.go, pkg/config/logconfig_test.go, pkg/customunit/handler.go, pkg/transaction/metric/metricscollector.go, pkg/transaction/metric/metricscollector_test.go
- Handle ComplianceAgent similar to Traceability Agent, minus marketplace functionality
- Create watch topic and auto subscribe to managed environments as well as api service instances in managed environments
- Utilize agent resource manage to trigger compliance agent processing
- Update watch resource handler to generate group/kind map via watch resources and/or directly sent in group/kind array
- Do not trigger credential validator in non-discovery agents
- Compliance agent resource apply config handling
=> APIGOV-30109 - Compliance agent handling in SDK

pkg/agent/agent.go, pkg/agent/cache/manager.go, pkg/agent/eventsync.go, pkg/agent/resource/manager.go, pkg/api/client_test.go, pkg/util/useragent.go, pkg/util/useragent_test.go, samples/watchclient/pkg/client/client.go
1. create runtime ID at startup
2. add it to the user agent
3. update process to rebuild cache
4. hardening to ensure cache is built properly
=> APIGOV-31098 - Add runtimeID to user-agent and update process to rebuild cache
